FROM node:13-alpine as build

WORKDIR /usr/src/app

COPY . .

RUN npm install -g ionic

RUN npm install

RUN ionic build --prod

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /usr/src/app/www/ /usr/share/nginx/html/

COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
