version: '3' 

services:
  ionic: 
    build:
      context: ./client 
      dockerfile: Dockerfile.dev
    volumes: 
      - ./client/src:/usr/src/app/client/src
    command: ionic serve --external --prod
    ports:
      - "8100:8100"

  express:
    build: server 
    ports:
      - "5000:5000"
    volumes: 
      - ./server:/usr/src/app

  database: 
    image: mongo
    ports:
      - "27017:27017"
    logging: 
      driver: none